language: go
go: "1.10"

notifications:
 email: false


before_install:
 - go version
 - sudo apt-get -qq update

install:
 - sudo apt-get -qq install -y gcc-multilib
 - sudo apt-get -qq install -y binutils-mingw-w64 mingw-w64
 - wget https://storage.googleapis.com/golang/go1.4.3.linux-amd64.tar.gz
 - tar -C $HOME -xzf go1.4.3.linux-amd64.tar.gz
 - mv $HOME/go $HOME/go1.4
 - (cd `which go | sed -e 's/\/bin\/go//g'`/src; GOOS=linux GOARCH=386 ./make.bash; GOOS=windows GOARCH=amd64 ./make.bash; GOOS=windows GOARCH=386 ./make.bash)
 - go get -u github.com/golang/dep/cmd/dep
 - go get -u github.com/jessevdk/go-assets-builder

script:
 - dep ensure
 - CLAY_ASSET_MODE=internal BUILD_ASSET=true BUILD_ASSET_SOURCE=../bastet CLAY_CONFIG_FILE_PATH=bastet/clay_config.json go generate -tags=prebuild prebuild/generate.go
 - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -tags "netgo sqlite_omit_load_extension" --ldflags '-extldflags "-static"' -o linux_amd64/clay
 - CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -a -tags "netgo sqlite_omit_load_extension" --ldflags '-extldflags "-static"' -o linux_386/clay
 - CC=x86_64-w64-mingw32-gcc LD=x86_64-w64-mingw32-ld CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -a --ldflags '-extldflags "-static"' -o windows_amd64/clay.exe
 - CC=i686-w64-mingw32-gcc LD=i686-w64-mingw32-ld CGO_ENABLED=1 GOOS=windows GOARCH=386 go build -a --ldflags '-extldflags "-static"' -o windows_386/clay.exe

after_success:
 - (cd linux_amd64; tar zcvf ../clay.bastet.linux-amd64.tgz clay)
 - (cd linux_386; tar zcvf ../clay.bastet.linux-386.tgz clay)
 - (cd windows_amd64; zip -r ../clay.bastet.windows-amd64.zip clay.exe)
 - (cd windows_386; zip -r ../clay.bastet.windows-386.zip clay.exe)
 - ls -la
 - ./upload.sh

